# Generated by Django 4.2 on 2026-04-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('school', 'School'), ('college', 'College'), ('university', 'University'), ('other', 'Other')], default='school', max_length=20)),
                ('institution', models.CharField(max_length=200)),
                ('degree', models.CharField(blank=True, help_text='e.g. SSC, HSC, BSc in Computer Science', max_length=200)),
                ('period', models.CharField(blank=True, help_text='e.g. 2019 – 2021', max_length=50)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='education/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first')),
            ],
            options={
                'verbose_name': 'Education entry',
                'verbose_name_plural': 'Education entries',
                'ordering': ['order', '-id'],
            },
        ),
    ]
